# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/mt6765-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gta7lite gta7litewifi,$(TARGET_DEVICE)),)

endif
